spring:
  application:
    name: gts-discovery

server:
  port: ${PORT:11001}
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.235:11000/eureka/
    registerWithEureka: true   #服务注册中心也会将自己作为客户端来尝试注册自己
    fetchRegistry: false  #由于注册中心的职责就是维护服务实例，它并不需要去检索服务，所以也设置为false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enable-self-preservation: false