spring:
  application:
    name: gts-discovery

server:
  port: ${PORT:11000}
eureka:
  instance:
    hostname: 192.168.1.235
  client:
    serviceUrl:
      defaultZone: http://192.168.1.235:11001/eureka/
